<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Form\Type\Finder;

use RK\AlmanacModule\Form\Type\Finder\Base\AbstractDateFinderType;

/**
 * Date finder form type implementation class.
 */
class DateFinderType extends AbstractDateFinderType
{
    // feel free to extend the base form type class here
}
