<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Helper;

use RK\AlmanacModule\Helper\Base\AbstractArchiveHelper;

/**
 * Archive helper implementation class.
 */
class ArchiveHelper extends AbstractArchiveHelper
{
    // feel free to extend the archive helper here
}
