<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Helper;

use RK\AlmanacModule\Helper\Base\AbstractImageHelper;

/**
 * Helper implementation class for image methods.
 */
class ImageHelper extends AbstractImageHelper
{
    // feel free to add your own convenience methods here
}
