<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Helper;

use RK\AlmanacModule\Helper\Base\AbstractNotificationHelper;

/**
 * Notification helper implementation class.
 */
class NotificationHelper extends AbstractNotificationHelper
{
    // feel free to extend the notification helper here
}
