services:
    rk_almanac_module.app_settings:
        class: RK\AlmanacModule\AppSettings
        arguments:
            - "@zikula_extensions_module.api.variable"
            - "@zikula_groups_module.group_repository"
