services:
    # Custom validators
    rk_almanac_module.validator.list_entry.validator:
        class: RK\AlmanacModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@rk_almanac_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: rk_almanac_module.validator.list_entry.validator }
