<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Form\Type;

use RK\AlmanacModule\Form\Type\Base\AbstractDateType;

/**
 * Date editing form type implementation class.
 */
class DateType extends AbstractDateType
{
    // feel free to extend the date editing form type class here
}
