<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\AlmanacModule;

use RK\AlmanacModule\Base\AbstractAlmanacModuleInstaller;

/**
 * Installer implementation class.
 */
class AlmanacModuleInstaller extends AbstractAlmanacModuleInstaller
{
    // feel free to extend the installer here
}
