<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Event;

use RK\AlmanacModule\Event\Base\AbstractFilterDateEvent;

/**
 * Event implementation class for filtering date processing.
 */
class FilterDateEvent extends AbstractFilterDateEvent
{
    // feel free to extend the event class here
}
