<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Entity;

use RK\AlmanacModule\Entity\Base\AbstractHookAssignmentEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entity implementation class for hooked object assignments.
 *
 * @ORM\Entity()
 * @ORM\Table(name="rk_alma_hookassignment")
 */
class HookAssignmentEntity extends AbstractHookAssignmentEntity
{
    // feel free to add your own methods here
}
