<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Form\Handler\Date;

use RK\AlmanacModule\Form\Handler\Date\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the date object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
