<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace RK\AlmanacModule\DependencyInjection;

use RK\AlmanacModule\DependencyInjection\Base\AbstractRKAlmanacExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKAlmanacExtension extends AbstractRKAlmanacExtension
{
    // custom enhancements can go here
}
