<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\AlmanacModule\HookSubscriber;

use RK\AlmanacModule\HookSubscriber\Base\AbstractDateFilterHooksSubscriber;

/**
 * Implementation class for filter hooks subscriber.
 */
class DateFilterHooksSubscriber extends AbstractDateFilterHooksSubscriber
{
    // feel free to add your own convenience methods here
}
