<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Zikula\Core\Doctrine\EntityAccess;
use RK\AlmanacModule\Traits\StandardFieldsTrait;
use RK\AlmanacModule\Validator\Constraints as AlmanacAssert;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for date entities.
 * The following annotation marks it as a mapped superclass so subclasses
 * inherit orm properties.
 *
 * @ORM\MappedSuperclass
 */
abstract class AbstractDateEntity extends EntityAccess
{
    /**
     * Hook standard fields behaviour embedding createdBy, updatedBy, createdDate, updatedDate fields.
     */
    use StandardFieldsTrait;

    /**
     * @var string The tablename this object maps to
     */
    protected $_objectType = 'date';
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @Assert\Type(type="integer")
     * @Assert\NotNull()
     * @Assert\LessThan(value=1000000000)
     * @var integer $id
     */
    protected $id = 0;
    
    /**
     * the current workflow state
     *
     * @ORM\Column(length=20)
     * @Assert\NotBlank()
     * @AlmanacAssert\ListEntry(entityName="date", propertyName="workflowState", multiple=false)
     * @var string $workflowState
     */
    protected $workflowState = 'initial';
    
    /**
     * The title will be the identifier for the date
     *
     * @ORM\Column(length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="0", max="255")
     * @var string $dateTitle
     */
    protected $dateTitle = '';
    
    /**
     * here you can tell a bit about the date
     *
     * @ORM\Column(type="text", length=20000)
     * @Assert\NotNull()
     * @Assert\Length(min="0", max="20000")
     * @var text $dateDescription
     */
    protected $dateDescription = '';
    
    /**
     * if allDay is true the date has no begin and end. Only single day dates are possible.
     *
     * @ORM\Column(type="boolean")
     * @Assert\NotNull()
     * @Assert\Type(type="bool")
     * @var boolean $allDay
     */
    protected $allDay = true;
    
    /**
     * complete day
     *
     * @ORM\Column(type="date")
     * @Assert\NotNull()
     * @Assert\Date()
     * @var date $allDayDate
     */
    protected $allDayDate;
    
    /**
     * Begin of the date
     *
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\DateTime()
     * @var DateTime $startDate
     */
    protected $startDate;
    
    /**
     * end of the date
     *
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\DateTime()
     * @Assert\Expression("value > this.getStartDate()")
     * @var DateTime $endDate
     */
    protected $endDate;
    
    /**
     * Date image meta data array.
     *
     * @ORM\Column(type="array")
     * @Assert\Type(type="array")
     * @var array $dateImageMeta
     */
    protected $dateImageMeta = [];
    
    /**
     * you can upload one image
     *
     * @ORM\Column(length=255, nullable=true)
     * @Assert\Length(min="0", max="255")
     * @Assert\File(
     *    mimeTypes = {"image/*"}
     * )
     * @Assert\Image(
     * )
     * @var string $dateImage
     */
    protected $dateImage = null;
    
    /**
     * Full date image path as url.
     *
     * @Assert\Type(type="string")
     * @var string $dateImageUrl
     */
    protected $dateImageUrl = '';
    
    /**
     * you can add a date URL
     *
     * @ORM\Column(length=255)
     * @Assert\NotNull()
     * @Assert\Length(min="0", max="255")
     * @Assert\Url(checkDNS=false)
     * @var string $dateUrl
     */
    protected $dateUrl = '';
    
    
    /**
     * @ORM\OneToMany(targetEntity="\RK\AlmanacModule\Entity\DateCategoryEntity", 
     *                mappedBy="entity", cascade={"all"}, 
     *                orphanRemoval=true)
     * @var \RK\AlmanacModule\Entity\DateCategoryEntity
     */
    protected $categories = null;
    
    
    /**
     * DateEntity constructor.
     *
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     */
    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }
    
    /**
     * Returns the _object type.
     *
     * @return string
     */
    public function get_objectType()
    {
        return $this->_objectType;
    }
    
    /**
     * Sets the _object type.
     *
     * @param string $_objectType
     *
     * @return void
     */
    public function set_objectType($_objectType)
    {
        if ($this->_objectType != $_objectType) {
            $this->_objectType = $_objectType;
        }
    }
    
    
    /**
     * Returns the id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Sets the id.
     *
     * @param integer $id
     *
     * @return void
     */
    public function setId($id)
    {
        if (intval($this->id) !== intval($id)) {
            $this->id = intval($id);
        }
    }
    
    /**
     * Returns the workflow state.
     *
     * @return string
     */
    public function getWorkflowState()
    {
        return $this->workflowState;
    }
    
    /**
     * Sets the workflow state.
     *
     * @param string $workflowState
     *
     * @return void
     */
    public function setWorkflowState($workflowState)
    {
        if ($this->workflowState !== $workflowState) {
            $this->workflowState = isset($workflowState) ? $workflowState : '';
        }
    }
    
    /**
     * Returns the date title.
     *
     * @return string
     */
    public function getDateTitle()
    {
        return $this->dateTitle;
    }
    
    /**
     * Sets the date title.
     *
     * @param string $dateTitle
     *
     * @return void
     */
    public function setDateTitle($dateTitle)
    {
        if ($this->dateTitle !== $dateTitle) {
            $this->dateTitle = isset($dateTitle) ? $dateTitle : '';
        }
    }
    
    /**
     * Returns the date description.
     *
     * @return text
     */
    public function getDateDescription()
    {
        return $this->dateDescription;
    }
    
    /**
     * Sets the date description.
     *
     * @param text $dateDescription
     *
     * @return void
     */
    public function setDateDescription($dateDescription)
    {
        if ($this->dateDescription !== $dateDescription) {
            $this->dateDescription = isset($dateDescription) ? $dateDescription : '';
        }
    }
    
    /**
     * Returns the all day.
     *
     * @return boolean
     */
    public function getAllDay()
    {
        return $this->allDay;
    }
    
    /**
     * Sets the all day.
     *
     * @param boolean $allDay
     *
     * @return void
     */
    public function setAllDay($allDay)
    {
        if (boolval($this->allDay) !== boolval($allDay)) {
            $this->allDay = boolval($allDay);
        }
    }
    
    /**
     * Returns the all day date.
     *
     * @return date
     */
    public function getAllDayDate()
    {
        return $this->allDayDate;
    }
    
    /**
     * Sets the all day date.
     *
     * @param date $allDayDate
     *
     * @return void
     */
    public function setAllDayDate($allDayDate)
    {
        if ($this->allDayDate !== $allDayDate) {
            if (!(null == $allDayDate && empty($allDayDate)) && !(is_object($allDayDate) && $allDayDate instanceOf \DateTimeInterface)) {
                $allDayDate = new \DateTime($allDayDate);
            }
            
            if (null === $allDayDate || empty($allDayDate)) {
                $allDayDate = new \DateTime();
            }
            
            if ($this->allDayDate != $allDayDate) {
                $this->allDayDate = $allDayDate;
            }
        }
    }
    
    /**
     * Returns the start date.
     *
     * @return DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }
    
    /**
     * Sets the start date.
     *
     * @param DateTime $startDate
     *
     * @return void
     */
    public function setStartDate($startDate)
    {
        if ($this->startDate !== $startDate) {
            if (!(null == $startDate && empty($startDate)) && !(is_object($startDate) && $startDate instanceOf \DateTimeInterface)) {
                $startDate = new \DateTime($startDate);
            }
            
            if (null === $startDate || empty($startDate)) {
                $startDate = new \DateTime();
            }
            
            if ($this->startDate != $startDate) {
                $this->startDate = $startDate;
            }
        }
    }
    
    /**
     * Returns the end date.
     *
     * @return DateTime
     */
    public function getEndDate()
    {
        return $this->endDate;
    }
    
    /**
     * Sets the end date.
     *
     * @param DateTime $endDate
     *
     * @return void
     */
    public function setEndDate($endDate)
    {
        if ($this->endDate !== $endDate) {
            if (!(null == $endDate && empty($endDate)) && !(is_object($endDate) && $endDate instanceOf \DateTimeInterface)) {
                $endDate = new \DateTime($endDate);
            }
            
            if (null === $endDate || empty($endDate)) {
                $endDate = new \DateTime();
            }
            
            if ($this->endDate != $endDate) {
                $this->endDate = $endDate;
            }
        }
    }
    
    /**
     * Returns the date image.
     *
     * @return string
     */
    public function getDateImage()
    {
        return $this->dateImage;
    }
    
    /**
     * Sets the date image.
     *
     * @param string $dateImage
     *
     * @return void
     */
    public function setDateImage($dateImage)
    {
        if ($this->dateImage !== $dateImage) {
            $this->dateImage = $dateImage;
        }
    }
    
    /**
     * Returns the date image url.
     *
     * @return string
     */
    public function getDateImageUrl()
    {
        return $this->dateImageUrl;
    }
    
    /**
     * Sets the date image url.
     *
     * @param string $dateImageUrl
     *
     * @return void
     */
    public function setDateImageUrl($dateImageUrl)
    {
        if ($this->dateImageUrl !== $dateImageUrl) {
            $this->dateImageUrl = $dateImageUrl;
        }
    }
    
    /**
     * Returns the date image meta.
     *
     * @return array
     */
    public function getDateImageMeta()
    {
        return $this->dateImageMeta;
    }
    
    /**
     * Sets the date image meta.
     *
     * @param array $dateImageMeta
     *
     * @return void
     */
    public function setDateImageMeta($dateImageMeta = [])
    {
        if ($this->dateImageMeta !== $dateImageMeta) {
            $this->dateImageMeta = $dateImageMeta;
        }
    }
    
    /**
     * Returns the date url.
     *
     * @return string
     */
    public function getDateUrl()
    {
        return $this->dateUrl;
    }
    
    /**
     * Sets the date url.
     *
     * @param string $dateUrl
     *
     * @return void
     */
    public function setDateUrl($dateUrl)
    {
        if ($this->dateUrl !== $dateUrl) {
            $this->dateUrl = isset($dateUrl) ? $dateUrl : '';
        }
    }
    
    /**
     * Returns the categories.
     *
     * @return ArrayCollection[]
     */
    public function getCategories()
    {
        return $this->categories;
    }
    
    
    /**
     * Sets the categories.
     *
     * @param ArrayCollection $categories List of categories
     *
     * @return void
     */
    public function setCategories(ArrayCollection $categories)
    {
        foreach ($this->categories as $category) {
            if (false === $key = $this->collectionContains($categories, $category)) {
                $this->categories->removeElement($category);
            } else {
                $categories->remove($key);
            }
        }
        foreach ($categories as $category) {
            $this->categories->add($category);
        }
    }
    
    /**
     * Checks if a collection contains an element based only on two criteria (categoryRegistryId, category).
     *
     * @param ArrayCollection $collection Given collection
     * @param \RK\AlmanacModule\Entity\DateCategoryEntity $element Element to search for
     *
     * @return bool|int
     */
    private function collectionContains(ArrayCollection $collection, \RK\AlmanacModule\Entity\DateCategoryEntity $element)
    {
        foreach ($collection as $key => $category) {
            /** @var \RK\AlmanacModule\Entity\DateCategoryEntity $category */
            if ($category->getCategoryRegistryId() == $element->getCategoryRegistryId()
                && $category->getCategory() == $element->getCategory()
            ) {
                return $key;
            }
        }
    
        return false;
    }
    
    
    
    /**
     * Creates url arguments array for easy creation of display urls.
     *
     * @return array List of resulting arguments
     */
    public function createUrlArgs()
    {
        return [
            'id' => $this->getId()
        ];
    }
    
    /**
     * Returns the primary key.
     *
     * @return integer The identifier
     */
    public function getKey()
    {
        return $this->getId();
    }
    
    /**
     * Determines whether this entity supports hook subscribers or not.
     *
     * @return boolean
     */
    public function supportsHookSubscribers()
    {
        return true;
    }
    
    /**
     * Return lower case name of multiple items needed for hook areas.
     *
     * @return string
     */
    public function getHookAreaPrefix()
    {
        return 'rkalmanacmodule.ui_hooks.dates';
    }
    
    /**
     * Returns an array of all related objects that need to be persisted after clone.
     * 
     * @param array $objects Objects that are added to this array
     * 
     * @return array List of entity objects
     */
    public function getRelatedObjectsToPersist(&$objects = [])
    {
        return [];
    }
    
    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     *
     * @return string The output string for this entity
     */
    public function __toString()
    {
        return 'Date ' . $this->getKey() . ': ' . $this->getDateTitle();
    }
    
    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a quite simple shallow copy.
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.php.net/manual/en/language.oop5.cloning.php
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     */
    public function __clone()
    {
        // if the entity has no identity do nothing, do NOT throw an exception
        if (!$this->id) {
            return;
        }
    
        // otherwise proceed
    
        // unset identifier
        $this->setId(0);
    
        // reset workflow
        $this->setWorkflowState('initial');
    
        // reset upload fields
        $this->setDateImage(null);
        $this->setDateImageMeta([]);
        $this->setDateImageUrl('');
    
        $this->setCreatedBy(null);
        $this->setCreatedDate(null);
        $this->setUpdatedBy(null);
        $this->setUpdatedDate(null);
    
    
        // clone categories
        $categories = $this->categories;
        $this->categories = new ArrayCollection();
        foreach ($categories as $c) {
            $newCat = clone $c;
            $this->categories->add($newCat);
            $newCat->setEntity($this);
        }
    }
}
