<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\AlmanacModule\Entity\DateEntity;

/**
 * Event base class for filtering date processing.
 */
class AbstractFilterDateEvent extends Event
{
    /**
     * @var DateEntity Reference to treated entity instance.
     */
    protected $date;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterDateEvent constructor.
     *
     * @param DateEntity $date Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(DateEntity $date, array $entityChangeSet = [])
    {
        $this->date = $date;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return DateEntity
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
