<?php
/**
 * Almanac.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.1 (https://modulestudio.de).
 */

namespace RK\AlmanacModule\Entity\Factory\Base;

use RK\AlmanacModule\Entity\DateEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * Initialises a given date instance.
     *
     * @param DateEntity $entity The newly created entity instance
     *
     * @return DateEntity The updated entity instance
     */
    public function initDate(DateEntity $entity)
    {

        return $entity;
    }

}
